# Generated by Django 6.0.1 on 2026-01-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.CharField(default='General Doctor', max_length=100),
            preserve_default=False,
        ),
    ]
