# Generated by Django 6.0.1 on 2026-01-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='instructions',
            field=models.TextField(blank=True, default='Please bring your ID and reach 15 minutes early.'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor'),
            preserve_default=False,
        ),
    ]
