# Generated by Django 6.0.1 on 2026-01-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_patient_created_at_alter_patient_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='specialty',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='instructions',
            field=models.TextField(blank=True, default='Please arrive 10 minutes early.'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
